const crypto = require("crypto");

// Excludes visually-confusable characters (0/O, 1/I/L) so a human reading
// a key aloud or typing it in never has to guess which glyph they meant.
const ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"; // 32 symbols → 5 bits/char
const SEGMENT_LENGTH = 4;
const SEGMENT_COUNT = 3; // PLC-XXXX-XXXX-XXXX — 12 random chars ≈ 60 bits entropy

function assertPepper() {
  const pepper = process.env.PRODUCT_KEY_PEPPER;
  if (!pepper || pepper.length < 16) {
    throw new Error(
      "PRODUCT_KEY_PEPPER is missing or too short. Set a long random value in .env before generating or activating product keys."
    );
  }
  return pepper;
}

/**
 * Cryptographically secure random segment, drawn from ALPHABET using
 * crypto.randomInt (CSPRNG-backed) — never Math.random(), never a
 * predictable/sequential source.
 */
function randomSegment(length = SEGMENT_LENGTH) {
  let segment = "";
  for (let i = 0; i < length; i++) {
    segment += ALPHABET[crypto.randomInt(0, ALPHABET.length)];
  }
  return segment;
}

/**
 * generateProductKey(productCode)
 * Returns the raw key string ("PLC-4F2A-9K1B-77QX") — the ONLY moment
 * this value exists in full. Callers must hash it immediately (see
 * hashProductKey) and must not persist the raw value anywhere; return it
 * to the caller exactly once, in the generation API response.
 */
function generateProductKey(productCode) {
  const segments = Array.from({ length: SEGMENT_COUNT }, () => randomSegment());
  return `${productCode.toUpperCase()}-${segments.join("-")}`;
}

/**
 * hashProductKey(rawKey)
 * HMAC-SHA256 with a server-side pepper (PRODUCT_KEY_PEPPER), not a plain
 * SHA-256 digest — so a stolen database alone (without the pepper, which
 * lives only in the environment) is insufficient to test guesses against
 * the hash. A slow/salted password-style hash (bcrypt/argon2) is
 * deliberately NOT used here: unlike user passwords, these keys are
 * already high-entropy random secrets (~60 bits) generated by us, not
 * human-chosen — activation needs a fast, deterministic exact-match
 * lookup (WHERE keyHash = ?), which a per-hash salt would make
 * impossible without scanning every row.
 */
function hashProductKey(rawKey) {
  const pepper = assertPepper();
  return crypto.createHmac("sha256", pepper).update(rawKey.toUpperCase().trim()).digest("hex");
}

function lastFour(rawKey) {
  return rawKey.slice(-4);
}

/**
 * maskedKey(productCode, keyLastFour)
 * Reconstructs a display-safe representation from data we actually
 * store — never from the raw key, which we don't have after generation.
 */
function maskedKey(productCode, keyLastFour) {
  return `${productCode}-****-****-${keyLastFour}`;
}

module.exports = { generateProductKey, hashProductKey, lastFour, maskedKey };